name: Update Match Results

on:
  schedule:
    - cron: "17 * * * *"

  # Denna gör att du kan klicka på "Run workflow" manuellt i GitHub om du vill!
  workflow_dispatch:

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my Next.js API

        run: |
          curl -X GET "https://www.adamstahlbom.se/api/fetch-matches" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
